name: Sign Test File with Sigstore

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Check Cosign version
        run: cosign version

      - name: Sign password.txt
        run: |
          cosign sign-blob password.txt \
            --bundle password.sigstore.json \
            --yes

      - name: Upload Sigstore bundle
        uses: actions/upload-artifact@v6
        with:
          name: sigstore-bundle
          path: password.sigstore.json
